// js/data-beats.js

const allBeats = [
  {
    id: 1,
    title: "BB Do Anália",
    genre: "Funk",
    bpm: 132,
    key: "A#m",
    price: 139.90,
    priceDisplay: "$139.90",
    image: "imgs/capas/bbdoanalia.jpg",
    preview: "audios/previa-bb-do-analia.mp3",
    date: "2025-08-12",
    description: "Beat de Funk estilo Mc Gp x Mc Meno K ",
    vibe: ["MC Gp", "MC Menor K"],
    onPromotion: true
  },
  {
    id: 2,
    title: "Ela é Modelo",
    genre: "Funk",
    bpm: 120,
    key: "C#m",
    price: 149.90,
    priceDisplay: "$149.90",
    image: "imgs/capas/capaelaemodelo.jpg",
    preview: "audios/previa-ela-e-modelo.mp3",
    date: "2025-08-12",
    description: "Beat de funk estilo Menor Mc x Mc Don Juan",
    vibe: ["Menor Mc", "Mc Don Juan"]
  },
  {
    id: 3,
    title: "Lipo Pad",
    genre: "Funk",
    bpm: 123,
    key: "Bm",
    price: 149.90,
    priceDisplay: "$149.90",
    image: "imgs/capas/capalipolad.jpg",
    preview: "audios/lipopad-previa.mp3",
    date: "2025-08-12",
    description: "Beat de funk estilo Mc luuky x Mc Tuto",
    vibe: ["MC Luuky", "Mc Tuto"]
  },
  {
    id: 4,
    title: "Lacoste",
    genre: "Funk",
    bpm: 120,
    key: "Fm",
    price: 149.90,
    priceDisplay: "$149.90",
    image: "imgs/capas/capalacoste.jpg",
    preview: "audios/previa-lacoste.mp3",
    date: "2024-01-12",
    description: "Beat de funk estilo Mc Ig x Mc Lele Jp",
    vibe: ["MC Ig", "MC Lele Jp"]
  },
  {
    id: 5,
    title: "Maria",
    genre: "Trap",
    bpm: 138,
    key: "G#m",
    price: 139.90,
    priceDisplay: "$139.90",
    image: "imgs/capas/capamaria.jpg",
    preview: "audios/previamaria.mp3",
    date: "2025-08-12",
    description: "Beat de trap estilo Caio Luccas x Felipe Ret",
    vibe: ["Felipe Ret", "Caio Luccas"],
    onPromotion: true
  },
  {
    id: 6,
    title: "SLAP",
    genre: "Trap",
    bpm: 140,
    key: "Fm",
    price: 149.90,
    priceDisplay: "$149.90",
    image: "imgs/capas/capaslap.jpg",
    preview: "audios/previa-slap.mp3",
    date: "2024-01-12",
    description: "Beat de Trap estilo Leviano x Alee",
    vibe: ["Leviano", "Alee"]
  },
  {
    id: 7,
    title: "Folder",
    genre: "Trap",
    bpm: 126,
    key: "Gm",
    price: 149.90,
    priceDisplay: "$149.90",
    image: "imgs/capas/capafolder.jpg",
    preview: "audios/previa-folder.mp3",
    date: "2024-01-12",
    description: "Beat de trap estilo Yunk Vino x Veigh",
    vibe: ["Veigh", "Yunk Vino"]
  },
  {
    id: 8,
    title: "Fragments",
    genre: "Hood Trap",
    bpm: 140,
    key: "Fm",
    price: 149.90,
    priceDisplay: "$149.90",
    image: "imgs/capas/capafragments.jpg",
    preview: "audios/previa-fragments.mp3",
    date: "2024-01-12",
    description: "Beat de HoodTrap estilo Niink x Supernova",
    vibe: ["Niink", "Supernova"]
  },
  {
    id: 9,
    title: "Hermosa",
    genre: "Trap",
    bpm: 147,
    key: "Dm",
    price: 139.90,
    priceDisplay: "$139.90",
    image: "imgs/capas/capahermosa.jpg",
    preview: "audios/previa-hermosa.mp3",
    date: "2024-01-12",
    description: "Beat de trap estilo Vulgo Fk x Kayblack",
    vibe: ["Vulgo Fk", "Kayblack"],
    onPromotion: true
  },
  {
    id: 10,
    title: "ILYA",
    genre: "Trap",
    bpm: 122,
    key: "Cm",
    price: 149.90,
    priceDisplay: "$149.90",
    image: "imgs/capas/capailya.jpg",
    preview: "audios/previa-ilya.mp3",
    date: "2024-01-12",
    description: "Beat de trap estilo Tz da Coronel x Mc Cabelinho",
    vibe: ["Tz da Coronel", "Mc Cabelinho"]
  },
  {
    id: 11,
    title: "Yes Sir",
    genre: "Trap",
    bpm: 140,
    key: "G#m",
    price: 149.90,
    priceDisplay: "$149.90",
    image: "imgs/capas/capayessir.jpg",
    preview: "audios/previa-yessir.mp3",
    date: "2024-01-12",
    description: "Beat de Trap estilo Teto x Wiu",
    vibe: ["Teto", "Wiu"]
  },
  {
    id: 12,
    title: "No More New Jazz",
    genre: "New Jazz",
    bpm: 128,
    key: "Em",
    price: 149.90,
    priceDisplay: "$149.90",
    image: "imgs/capas/capanomore.jpg",
    preview: "audios/previa-nomore.mp3",
    date: "2024-01-12",
    description: "Beat de New Jazz estilo Lil Tecca",
    vibe: ["Lil Tecca"]
  }
];